SCRUM-3 Intentando

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,21 +46,25 @@ jobs:
       - name: Check SonarCloud Quality Gate
         id: quality_gate
         run: |
-            sleep 10  # wait for the analysis to be processed
-            ANALYSIS_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=amil-nicolas21_Parcial-Nro-2" | jq -r .projectStatus.status)
-            
-            echo "Quality Gate status: $ANALYSIS_STATUS"
-            
-            if [ "$ANALYSIS_STATUS" != "OK" ]; then
-              echo "❌ SonarCloud Quality Gate failed!"
-              exit 1
-            fi
+          sleep 10
+          ANALYSIS_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=amil-nicolas21_Parcial-Nro-2" | jq -r .projectStatus.status)
+          echo "Quality Gate status: $ANALYSIS_STATUS"
+          echo "quality_gate_status=$ANALYSIS_STATUS" >> $GITHUB_OUTPUT
+
+          if [ "$ANALYSIS_STATUS" != "OK" ]; then
+            echo "❌ SonarCloud Quality Gate failed!"
+            exit 1
+          fi
+      
 
       - name: Notify Test in Slacks
         if: always()
         run: |
                 COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-                if [ "${{ steps.test_step.outputs.test_result }}" -eq 0 ]; then
+                TEST_RESULT=${{ steps.test_step.outputs.test_result }}
+                QUALITY_GATE_STATUS=${{ steps.quality_gate.outputs.quality_gate_status }}
+          
+                if [ "$TEST_RESULT" -eq 0 ] && [ "$QUALITY_GATE_STATUS" = "OK" ]; then
                   COLOR="#2eb886"
                   STATUS="✅ Tests Passed"
                 else
