SCRUM-3 Intentando

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,18 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
+      - name: Check SonarCloud Quality Gate
+        id: quality_gate
+        run: |
+            sleep 10  # wait for the analysis to be processed
+            ANALYSIS_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=amil-nicolas21_Parcial-Nro-2" | jq -r .projectStatus.status)
+            
+            echo "Quality Gate status: $ANALYSIS_STATUS"
+            
+            if [ "$ANALYSIS_STATUS" != "OK" ]; then
+              echo "❌ SonarCloud Quality Gate failed!"
+              exit 1
+            fi
 
       - name: Notify Test in Slacks
         if: always()
